ecommerce/urls.py
from ecommerce.views import index,privacy_policy,update_order_status, terms_conditions, contact,about, wishlist_view, ajax_contact_form, remove_wishlist, order_detail, make_address_default, customer_dashboard,checkout_view, payment_failed_view, payment_completed_view, cart_view, update_cart, search_view, category_list_view, product_list_view, vendor_list_view , vendor_detail_view, category_product_list_view, product_detail_view, tag_list , filter_product, ajax_add_review, add_to_cart,add_to_wishlist, delete_item_from_cart
from django.urls import path
from django.urls import include 
from django.conf import settings
from django.conf.urls.static import static
app_name = "ecommerce"

urlpatterns = [
    #Homepage
    path("" , index, name = "index"),
    path('user/', include('userauths.urls')),
    path('categories/', category_list_view, name='category-list'),
    path('products/', product_list_view, name='product-list'),
    path('products/<pid>/', product_detail_view, name='product-detail'),    
    path('vendors/', vendor_list_view, name='vendor-list'),
    path('vendor/<vid>/', vendor_detail_view, name='vendor-detail'),
    path('category_product_list/<cid>/', category_product_list_view, name='category_product_list'),
    path('tags/<slug:tag_slug>/', tag_list, name='tags'),
    
    #Add Review 
    path('ajax-add-review/<pid>/', ajax_add_review, name="ajax-add-review"),

    path("search/", search_view, name = "search"),
    path('filter-products/', filter_product , name="filter-products"),
    
    
    
    path("add-to-cart/", add_to_cart, name = "add-to-cart"),

    #cart page
    path("cart/", cart_view, name = "cart"),

    #delete item from cart
    path("delete-from-cart/", delete_item_from_cart, name = "delete-from-cart"),
    #Update cart
    path("update-cart/", update_cart, name = "update-cart"),
    
    #checkout url
    path("checkout/", checkout_view, name = "checkout"),

    #Paypal
    path("paypal/", include('paypal.standard.ipn.urls')),
    
    #Payment Successful
    path("payment-completed/", payment_completed_view, name = "payment-completed"),
    
    #Payment Failed
    path("payment-failed/", payment_failed_view, name = "payment-failed"),
    
    #Dashboard  Url
    path("dashboard/", customer_dashboard, name = "dashboard"),
    
    #Order Detail
    path("dashboard/order/<int:id>", order_detail, name = "order-detail"),

    #making address default
    path("make-default-address/", make_address_default, name ="make-default-address"),

    path("wishlist/", wishlist_view, name ="wishlist"),
    
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),


    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),

    path('contact/', contact, name='contact'),
    path("ajax-contact-form/",ajax_contact_form,name="ajax-contact-form"),
    path('about/', about, name='about'),

    path('privacy-policy/', privacy_policy, name='privacy-policy'),
    
    path('terms-conditions/', terms_conditions, name='terms-conditions'),
    path('update_order_status/', update_order_status, name='update_order_status'),
]

ecommerceprj/urls.py
from django.contrib import admin
from django.urls import path , include


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecommerce.urls")),
    path("user/", include("userauths.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
     #Paypal
    path("paypal/", include('paypal.standard.ipn.urls')),

]


"""if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)"""

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/forms.py
from django import forms 
from ecommerce.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review =forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write review"}))
    
    class Meta:
        model = ProductReview
        fields = [ 'review' , 'rating']

ecommerce/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseNotAllowed
from django.db.models import Count, Avg
from django.http import  JsonResponse
from taggit.models import Tag
from ecommerce.models import Product, Category, Vendor, CartOrder, CartOrderItems, ProductImages, ProductReview, Wishlist_model, Address
from ecommerce.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
from django.urls  import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from userauths.models import Profile, contactUs
from django.db.models.functions import ExtractMonth
import calendar



def index(request):
    #products = Product.objects.all().order_by("-id")
    products = Product.objects.filter(product_status = "published", featured = True)
    context = {
        "products": products
    }

    return render(request, 'ecommerce/index.html', context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors" : vendors,
    }
    return render(request , "ecommerce/vendor-list.html", context)
    
    
 
def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published")

    
    
    context = {
        "vendor": vendor,
        "products": products,

    }

    return render(request, "ecommerce/vendor-detail.html", context)
  
    


def product_list_view(request):
    products = Product.objects.filter(product_status = "published")
    vendors = set(product.vendor for product in products)

    # Now 'vendors' is a list containing the 'vendor' attribute for each product
    
    context = {
        "products": products,
        'vendors': vendors

    }

    return render(request, 'ecommerce/product-list.html', context)
    

def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories": categories

    }

    return render(request, 'ecommerce/category-list.html', context)
    


def category_product_list_view(request, cid):
    category = Category.objects.get(cid = cid)
    products = Product.objects.filter(product_status = "published", category = category)

    context = {
        "category":category,
        "products": products,
    }
    return render(request, "ecommerce/category_product_list.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid = pid)
    #product = get_object_or_404(Product, pid = pid)
    vendor = product.vendor

    products = Product.objects.filter(category = product.category).exclude(pid = pid)[:8]

    reviews = ProductReview.objects.filter(product = product)

    average_rating = ProductReview.objects.filter(product = product).aggregate(rating = Avg('rating'))
    
    # Product Review form
    review_form = ProductReviewForm()
    make_review = True 

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user = request.user, product = product).count()

        if user_review_count > 0:
            make_review = True

    p_image = product.p_images.all()

    context = {
        "product":product,
        "review_form":review_form,
        "p_image":p_image,
        "reviews":reviews,
        "average_rating":average_rating,
        "products":products,
        "vendor":vendor,
        "make_review":make_review,
    }

    return render(request, "ecommerce/product-detail.html", context)



def tag_list(request, tag_slug = None):
    products = Product.objects.filter(product_status = "published").order_by("-id")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        products = products.filter(tags__in=[tag])


    context = {
        "products":products,
        "tag":tag
    }

    return render(request, "ecommerce/tag.html", context)





def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user = user,
        product =product,
        review = request.POST['review'],
        rating= request.POST['rating'],
    )
    
    context = {
        'user': user.username,
        'review' : request.POST['review'],
        'rating' : request.POST['rating'],
        
        
    }
    
    
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))
    
    return JsonResponse(
        {
        'bool' : True,
        'context' :  context,
        'average_reviews' : average_reviews,
        }
    )



def search_view(request):
    query = request.GET.get("q")

    products = Product.objects.filter(title__icontains = query).order_by("-date")

    context = {
        "products":products,
        "query":query,
    }

    return render(request, "ecommerce/search.html", context)



def filter_product(request):
    categories = request.GET.getlist('category[]') 
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']


    products = Product.objects.filter(product_status = "published").order_by("-id").distinct()
    
    products =products.filter(price__gte=min_price)
    products =products.filter(price__lte=max_price)
    
    if len(categories) > 0: 
        
        products = products.filter(category__id__in=categories).distinct()
        
    if len(vendors) > 0: 
        products = products.filter(vendor__id__in=vendors).distinct()
    
       
        
    data = render_to_string("ecommerce/async/product-list.html",{"products":products})
    
    return JsonResponse({"data":data})
    


def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image':request.GET['image'],
        'pid':request.GET['pid'],

    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
             cart_data = request.session['cart_data_obj']
             cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
             cart_data.update(cart_data)
             request.session['cart_data_obj'] = cart_data

        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data

    else:
        request.session['cart_data_obj'] = cart_product

    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})
    
    

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, "ecommerce/cart.html", {"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    
    else:
        messages.warning(request, "Your cart is empty")
        return redirect("ecommerce:index")
    

def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("ecommerce/async/cart-list.html",{"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    return JsonResponse({"data":context, 'totalcartitems': len(request.session['cart_data_obj'])})



def update_cart(request):
    cart_total_amount = 0 
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']
    
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty 
            request.session['cart_data_obj'] = cart_data

    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])

    context = render_to_string("ecommerce/async/cart-list.html",{"cart_data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    return JsonResponse({"data":context, 'totalcartitems': len(request.session['cart_data_obj'])})
        

@login_required
def checkout_view(request):
    cart_total_amount = 0
    total_amount = 0
    # Checking if cart_data_obj session exists
    if 'cart_data_obj' in request.session:
        #Getting total amount for Paypal Amount
        for p_id, item in request.session['cart_data_obj'].items():
            total_amount += int(item['qty']) * float(item['price'])
        # create order object  
        order = CartOrder.objects.create(
            user = request.user,
            price = total_amount
        )
        
        #Getting total amount for the cart
        for p_id, item in request.session['cart_data_obj'].items():

templates/ecommerce/checkout.html
{% extends "patials/base.html" %}

{% load static%} 
{% block content %}
<main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow">Home</a>
                    <span></span> Shop
                    <span></span> Checkout
                </div>
            </div>
        </div>
        <section class="mt-50 mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 mb-sm-15">
                        <div class="toggle_info">
                            <span><i class="fi-rs-user mr-10"></i><span class="text-muted">Already have an account?</span> <a href="#loginform" data-bs-toggle="collapse" class="collapsed" aria-expanded="false">Click here to login</a></span>
                        </div>
                        <div class="panel-collapse collapse login_form" id="loginform">
                            <div class="panel-body">
                                <p class="mb-30 font-sm">If you have shopped with us before, please enter your details below. If you are a new customer, please proceed to the Billing &amp; Shipping section.</p>
                                <form method="post">
                                    <div class="form-group">
                                        <input type="text" name="email" placeholder="Username Or Email">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" placeholder="Password">
                                    </div>
                                    <div class="login_footer form-group">
                                        <div class="chek-form">
                                            <div class="custome-checkbox">
                                                <input class="form-check-input" type="checkbox" name="checkbox" id="remember" value="">
                                                <label class="form-check-label" for="remember"><span>Remember me</span></label>
                                            </div>
                                        </div>
                                        <a href="#">Forgot password?</a>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-md" name="login">Log in</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="toggle_info">
                            <span><i class="fi-rs-label mr-10"></i><span class="text-muted">Have a coupon?</span> <a href="#coupon" data-bs-toggle="collapse" class="collapsed" aria-expanded="false">Click here to enter your code</a></span>
                        </div>
                        <div class="panel-collapse collapse coupon_form " id="coupon">
                            <div class="panel-body">
                                <p class="mb-30 font-sm">If you have a coupon code, please apply it below.</p>
                                <form method="post">
                                    <div class="form-group">
                                        <input type="text" placeholder="Enter Coupon Code...">
                                    </div>
                                    <div class="form-group">
                                        <button class="btn  btn-md" name="login">Apply Coupon</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-12">
                        <div class="divider mt-50 mb-50"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-25">
                            <h4>Billing Details</h4>
                        </div>
                        <div class="row">
                            <div class="col-lg-8 mb-48">
                                <div class="d-flex justify-content-between">
                                    <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                                </div>
                            </div>
                        </div>
                        <br>
                        <form method="post">
                            <div class="form-group">
                                <input type="text" required="" name="fname" value="{{request.user.username|title}}" placeholder="First name *">
                            </div>
                            <div class="form-group">
                                <input type="text" required="" name="lname" placeholder="mobile *" value="{{active_address.mobile}}">
                            </div>
                            <div class="form-group">
                                <input type="text" name="billing_address" value="{{active_address.address}}" required="" placeholder="Address *">
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <div class="order_review">
                            <div class="mb-20">
                                <h4>Your Orders</h4>
                            </div>
                            <div class="table-responsive order_table text-center">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Product</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {%for product_id,item in cart_data.items%}  
                                    
                                      <tr>
                                          <td class="image product-thumbnail"><img src="{{item.image}}" alt="#"></td>
                                        <td>
                                            <h6><a href="p{% url 'ecommerce:product-detail' item.pid %}">{{item.title}}</a></h6> <span class="product-qty">x 2</span>
                                            
                                        </td>
                                        <td>
                                            <h6 class="text-muted pl-20 pr-20">x {{item.qty}}</h6> 
                                        </td>
                                        <td>
                                            <h5 class="text-muted">{{item.price}}</h5>                 
                                        </td>
                                        
                                        <td>
                                            <h5 class="text-brand">${% widthratio item.price 1 item.qty %}</h5>                 
                                        </td>
                                      </tr>
                                       
                                      {%endfor%}
                                   <tr>
                                            <th>SubTotal</th>
                                            <td class="product-subtotal text-brand" colspan="2">${{cart_total_amount|floatformat:2}}</td>
                                        </tr>  
                                </tbody>
                            </table>
                             <div class="divider-2 mb-30"></div>
                            <a href="{%url 'ecommerce:cart'%}" class="btn btn-fill-out btn-block mt-30 mb-40">go back to cart </a>    
    
                            </div>               
                            </div>
                        </div>            
                                 
                             </div class="payment ml-30">
                                <h4 class="mb-30">Payment</h4>
                                <div class="payment_option">
                                    <div class="custome-radio">
                                        <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3">
                                        <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#cashOnDelivery" aria-controls="cashOnDelivery">Cash On Delivery</label>                                        
                                    </div>
                                    <div class="custome-radio">
                                        <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4">
                                        <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#cardPayment" aria-controls="cardPayment">Card Payment</label>                                        
                                    </div>
                                    <div class="custome-radio">
                                        <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios5">
                                        <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Paypal</label>                                        
                                    </div>
                                </div>
                            </div>
                           
                            <!--<a href="#" class="btn btn-fill-out btn-block mt-30">Place Order</a>-->
                        </div> 
                        <div class="w-50 d-flex justify-content-between align-to-left">
                            {{paypal_payment_button.render}}
                        </div>
                        <style>
                            .align-to-left {
                                margin-left: 50px; /* Adjust the margin value as needed */
                            }
                            
                        </style>
                        </div>
                        
                    </div>
                </div>
            </div>
        </section>
    </main>

  

{% endblock content %}

templates/ecommerce/wishlist.html
{% extends "patials/base.html" %}

{% load static%} 
{% block content %}
<main class="main" id="wishlist-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow">Home</a>
                    <span></span> Shop
                    <span></span> Your Wishlist
                </div>
            </div>
        </div>
        <section class="mt-50 mb-50">
            <div class="container">
                <h1 class="heading-2 mb-10">Your Wishlist</h1>
                <h6 class="text-body">You Have <span class="text-brand">{{wishlist.count}}</span> Wishes</h6>

                <br>
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table shopping-summery text-center clean">
                                <thead>
                                    <tr class="main-heading">
                                        <th scope="col">Image</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">Stock Status</th>
                                        <th scope="col">Action</th>
                                        <th scope="col">Remove</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for w in w %}
                                    <tr>
                                        <td class="image product-thumbnail"><img src="{{ w.product.image.url }}" alt="#"></td>
                                        <td class="product-des product-name">
                                            {% if w.product.pid %}
                                                <a href="{% url 'ecommerce:product-detail' w.product.pid %}">{{w.product.title|truncatechars:30}}</a>
                                            {% else %}
                                                Product ID not available
                                            {% endif %}                                            
                                        </td>
                                        <td class="price" data-title="Price"><span class="current-product-price-{{ w.product.id }}">${{w.product.price|floatformat:2}}</span></td>
                                        <td class="text-center detail-info" data-title="stock">
                                            <span class="stock-status in-stock mb-0"> {% if w.product.in_stock %} In Stock {% else %} Out Of Stock {% endif %}</span>
                                        </td>
                                        <!--<td class="action" data-title="Refrech"><a href="#" class="text-body"><i class="fi-rs-refresh"></i></a></td>-->
                                        <td class="text-right" data-title="Crat">
                                            <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{w.product.id}}">
                                            <input type="hidden" class="product-pid-{{w.product.id}}" value="{{w.product.pid}}">
                                            <input type="hidden" class="product-image-{{w.product.id}}" value="{{w.product.image.url}}">
                                            <input type="hidden" class="product-id-{{w.product.id}}" value="{{w.product.id}}">
                                            <input type="hidden" class="product-title-{{w.product.id}}" value="{{w.product.title}}">
                                            
                                            <button class="btn btn-sm add add-to-cart-btn" data-index="{{w.product.id}}"> {% if w.product.in_stock %} Add to cart {% else %} Contact Us {% endif %} </button>
                                        </td>
                                        <td class="action text-center" data-title="Remove">
                                            <button style="border:none; background:none" class="text-body delete-wishlist-product" data-wishlist-product="{{ w.id }}">
                                                <i class="fi-rs-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td>
                                            <p>Nothing in wishlist Yet.</p>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="cart-action text-end">
                            <a class="btn" href="{% url 'ecommerce:product-list' %}"><i class="fi-rs-shopping-bag mr-10"></i>Continue Shopping</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}